### PR TITLE
Add family_id CLI option

### PR DESCRIPTION
**Pull request by dnil**
RankScore needs a family_id in Scout. Testing now, brb...

### CODE REVIEW

**Comment by dnil** [comment]
So far, so good:
Screenshot 2021-02-01 at 15 47 49
(RFC1 and DIP2B are on the test panel..)

**Comment by dnil** [comment]
Ok, looks like this is now working on the STR filters branch of Scout - in master any day. Merging!

**Comment by katerinaoleynikova** [comment]
Good day,

Thank you for this tool! :)
Could you please clarify why this option was added? Is it smth very important for the results?
Thank you so much.

**Comment by dnil** [comment]
You are most welcome - fun to hear from more users! 😸 

No, the `--family_id` option will prepend your arbitrary family id string to the VCF RankScore INFO field. This can be useful downstream, e.g. if you are visualising with [Scout](https://github.com/Clinical-Genomics/scout), but is otherwise purely cosmetic.

**Comment by katerinaoleynikova** [comment]
Thanks!

**Pull request merged**
